spring:
  application:
    name: config-client
  cloud:
    config:
      label: config
      name: config
      profile: dev
      uri: http://localhost:8888
    

  config:
      import: optional:configserver:http://localhost:8888


server:
  port: 8088